# Generated by Django 4.2 on 2023-12-03 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='node',
            name='Data',
        ),
        migrations.AddField(
            model_name='node',
            name='Author',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='Music_file',
            field=models.FileField(default=1450, upload_to='Audio_files'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='Title',
            field=models.CharField(default='new title', max_length=350),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Music_data',
        ),
        migrations.AddField(
            model_name='linkedlist',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.node'),
        ),
    ]
