# Generated by Django 4.2 on 2023-12-05 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_linkedlist_remove_node_data_node_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedlist',
            name='tail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tail_node', to='App.node'),
        ),
        migrations.AlterField(
            model_name='linkedlist',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_node', to='App.node'),
        ),
        migrations.AlterField(
            model_name='node',
            name='Music_file',
            field=models.FileField(null=True, upload_to='Audio_files'),
        ),
    ]
