# Generated by Django 4.2 on 2023-12-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_linkedlist_tail_alter_linkedlist_head_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedlist',
            name='head',
        ),
        migrations.RemoveField(
            model_name='linkedlist',
            name='tail',
        ),
    ]
