# Generated by Django 4.2 on 2023-12-05 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_linkedlist_head_remove_linkedlist_tail'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedlist',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_node', to='App.node'),
        ),
        migrations.AddField(
            model_name='linkedlist',
            name='tail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tail_node', to='App.node'),
        ),
    ]
