# Generated by Django 5.0 on 2023-12-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_linkedlist_head_linkedlist_tail'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='Title_Img',
            field=models.ImageField(null=True, upload_to='Images'),
        ),
    ]
