# Generated by Django 5.0 on 2023-12-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_node_title_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='Title_Img',
        ),
    ]
