# Generated by Django 4.2 on 2023-12-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_remove_node_title_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedlist',
            name='size',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
