# Generated by Django 4.2 on 2023-12-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_linkedlist_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedlist',
            name='size',
        ),
    ]
